[features]
seeds = false
skip-lint = false
[programs.localnet]
wsos_dao_voting_app = "3gQfmeiQb9zfP4Utg22Vn2RJvzAwx264oaNrctRNd91W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xalexus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
